##
# Example Ansible playbook that uses the PostgreSQL module.
#
# This installs PostgreSQL on an Ubuntu system, creates a database called
# "myapp" and a user called "django" with password "mysupersecretpassword"
# with access to the "myapp" database.
#
---
  - name: apt-get install
    apt: pkg={{ item }} update_cache=yes state=present
    with_items:
      - postgresql
      - libpq-dev
      - python-psycopg2
    become: yes
    become_user: root
